export type TagSeed = {
  key: string;
  labelDe: string;
  category: 'trigger' | 'nutrient' | 'group';
  isAnalysed: boolean;
  /**
   * Pre-declared lag window. Every tag commits to ONE window before any data
   * exists — testing all tags against all windows would multiply the number of
   * hypotheses and produce false positives by construction.
   */
  primaryWindow?: 'immediate' | 'early' | 'mid' | 'late' | 'next_day';
  /** Below this many grams a day does not count as exposed. */
  minDoseGrams?: number;
  descriptionDe?: string;
};

/** Intolerance / trigger candidates. */
const TRIGGERS: TagSeed[] = [
  {
    key: 'gluten',
    labelDe: 'Gluten / Weizen',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'late',
    minDoseGrams: 10,
  },
  {
    key: 'lactose',
    labelDe: 'Laktose',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'early',
    minDoseGrams: 5,
  },
  {
    key: 'milk_protein',
    labelDe: 'Milchprotein (Casein)',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'late',
    minDoseGrams: 5,
  },
  {
    key: 'fructose',
    labelDe: 'Fruktose',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'mid',
    minDoseGrams: 5,
  },
  {
    key: 'sorbitol',
    labelDe: 'Sorbit / Zuckeralkohole',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'mid',
    minDoseGrams: 2,
  },
  {
    key: 'fodmap_high',
    labelDe: 'FODMAP-reich',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'mid',
    minDoseGrams: 10,
  },
  {
    key: 'histamine',
    labelDe: 'Histamin',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'immediate',
    minDoseGrams: 5,
  },
  {
    key: 'histamine_liberator',
    labelDe: 'Histaminliberator',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'immediate',
    minDoseGrams: 5,
  },
  {
    key: 'tyramine',
    labelDe: 'Tyramin',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'immediate',
    minDoseGrams: 5,
  },
  {
    key: 'nightshade',
    labelDe: 'Nachtschattengewächse',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'late',
    minDoseGrams: 20,
  },
  {
    key: 'legume',
    labelDe: 'Hülsenfrüchte',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'mid',
    minDoseGrams: 20,
  },
  {
    key: 'soy',
    labelDe: 'Soja',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'mid',
    minDoseGrams: 5,
  },
  {
    key: 'egg',
    labelDe: 'Ei',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'late',
    minDoseGrams: 10,
  },
  {
    key: 'nuts',
    labelDe: 'Nüsse',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'early',
    minDoseGrams: 5,
  },
  {
    key: 'peanut',
    labelDe: 'Erdnuss',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'early',
    minDoseGrams: 5,
  },
  {
    key: 'fish',
    labelDe: 'Fisch',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'early',
    minDoseGrams: 20,
  },
  {
    key: 'shellfish',
    labelDe: 'Krusten- / Schalentiere',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'immediate',
    minDoseGrams: 20,
  },
  {
    key: 'sesame',
    labelDe: 'Sesam',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'early',
    minDoseGrams: 2,
  },
  {
    key: 'celery',
    labelDe: 'Sellerie',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'early',
    minDoseGrams: 2,
  },
  {
    key: 'mustard',
    labelDe: 'Senf',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'early',
    minDoseGrams: 2,
  },
  {
    key: 'sulfite',
    labelDe: 'Sulfite',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'early',
    minDoseGrams: 1,
  },
  {
    key: 'yeast',
    labelDe: 'Hefe',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'mid',
    minDoseGrams: 2,
  },
  {
    key: 'caffeine',
    labelDe: 'Koffein',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'early',
    minDoseGrams: 1,
  },
  {
    key: 'alcohol',
    labelDe: 'Alkohol',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'immediate',
    minDoseGrams: 5,
  },
  {
    key: 'glutamate',
    labelDe: 'Glutamat (MSG)',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'early',
    minDoseGrams: 1,
  },
  {
    key: 'artificial_sweetener',
    labelDe: 'Süßstoffe',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'mid',
    minDoseGrams: 1,
  },
  {
    key: 'food_coloring',
    labelDe: 'Farbstoffe',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'mid',
    minDoseGrams: 1,
  },
  {
    key: 'preservative',
    labelDe: 'Konservierungsstoffe',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'mid',
    minDoseGrams: 1,
  },
  {
    key: 'salicylate',
    labelDe: 'Salicylate',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'late',
    minDoseGrams: 5,
  },
  {
    key: 'capsaicin',
    labelDe: 'Scharf (Capsaicin)',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'immediate',
    minDoseGrams: 1,
  },
  {
    key: 'citrus',
    labelDe: 'Zitrusfrüchte',
    category: 'trigger',
    isAnalysed: true,
    primaryWindow: 'early',
    minDoseGrams: 20,
  },
];

/** Dietary patterns with a plausible effect on inflammation. Slow by nature. */
const NUTRIENTS: TagSeed[] = [
  {
    key: 'omega3',
    labelDe: 'Omega-3',
    category: 'nutrient',
    isAnalysed: true,
    primaryWindow: 'next_day',
    minDoseGrams: 5,
  },
  {
    key: 'oily_fish',
    labelDe: 'Fetter Seefisch',
    category: 'nutrient',
    isAnalysed: true,
    primaryWindow: 'next_day',
    minDoseGrams: 20,
  },
  {
    key: 'arachidonic_acid',
    labelDe: 'Arachidonsäure',
    category: 'nutrient',
    isAnalysed: true,
    primaryWindow: 'next_day',
    minDoseGrams: 20,
  },
  {
    key: 'red_meat',
    labelDe: 'Rotes Fleisch',
    category: 'nutrient',
    isAnalysed: true,
    primaryWindow: 'next_day',
    minDoseGrams: 50,
  },
  {
    key: 'processed_meat',
    labelDe: 'Wurst / verarbeitetes Fleisch',
    category: 'nutrient',
    isAnalysed: true,
    primaryWindow: 'next_day',
    minDoseGrams: 20,
  },
  {
    key: 'ultra_processed',
    labelDe: 'Hochverarbeitet',
    category: 'nutrient',
    isAnalysed: true,
    primaryWindow: 'next_day',
    minDoseGrams: 50,
  },
  {
    key: 'high_sugar',
    labelDe: 'Zuckerreich',
    category: 'nutrient',
    isAnalysed: true,
    primaryWindow: 'next_day',
    minDoseGrams: 20,
  },
  {
    key: 'whole_grain',
    labelDe: 'Vollkorn',
    category: 'nutrient',
    isAnalysed: true,
    primaryWindow: 'next_day',
    minDoseGrams: 30,
  },
  {
    key: 'fermented',
    labelDe: 'Fermentiert',
    category: 'nutrient',
    isAnalysed: true,
    primaryWindow: 'next_day',
    minDoseGrams: 20,
  },
  {
    key: 'olive_oil',
    labelDe: 'Olivenöl',
    category: 'nutrient',
    isAnalysed: true,
    primaryWindow: 'next_day',
    minDoseGrams: 5,
  },
  {
    key: 'vegetable_rich',
    labelDe: 'Gemüsereich',
    category: 'nutrient',
    isAnalysed: true,
    primaryWindow: 'next_day',
    minDoseGrams: 100,
  },
];

/** Descriptive only — used to filter the food library, never analysed. */
const GROUPS: TagSeed[] = [
  {
    key: 'dairy',
    labelDe: 'Milchprodukte',
    category: 'group',
    isAnalysed: false,
  },
  {
    key: 'grain',
    labelDe: 'Getreideprodukte',
    category: 'group',
    isAnalysed: false,
  },
  { key: 'meat', labelDe: 'Fleisch', category: 'group', isAnalysed: false },
  {
    key: 'fish_group',
    labelDe: 'Fisch & Meeresfrüchte',
    category: 'group',
    isAnalysed: false,
  },
  { key: 'vegetable', labelDe: 'Gemüse', category: 'group', isAnalysed: false },
  { key: 'fruit', labelDe: 'Obst', category: 'group', isAnalysed: false },
  {
    key: 'sweets',
    labelDe: 'Süßigkeiten',
    category: 'group',
    isAnalysed: false,
  },
  {
    key: 'beverage',
    labelDe: 'Getränke',
    category: 'group',
    isAnalysed: false,
  },
  {
    key: 'alcoholic_beverage',
    labelDe: 'Alkoholische Getränke',
    category: 'group',
    isAnalysed: false,
  },
  {
    key: 'ready_meal',
    labelDe: 'Fertiggericht',
    category: 'group',
    isAnalysed: false,
  },
  {
    key: 'supplement',
    labelDe: 'Nahrungsergänzung',
    category: 'group',
    isAnalysed: false,
  },
];

export const FOOD_TAGS: TagSeed[] = [...TRIGGERS, ...NUTRIENTS, ...GROUPS];
